"""
agent/nodes/sql_generation.py — Node [4]: LLM SQL Generator Agent.
Generates BigQuery SQL targeting views_<role>.* views. Biases toward aggregation
when output_mode='summary'. Incorporates structured error feedback on retries.
"""

import time
from typing import Dict, Any
from langchain_core.messages import SystemMessage, HumanMessage

from agent.state import GraphState
from agent.groq_client import invoke_groq_with_retry
from agent.logging_store import DEFAULT_LOGGING_STORE

SQL_GEN_SYSTEM_PROMPT = """You are an expert BigQuery SQL generator for an enterprise NBFC data warehouse.
Your job is to produce a single, valid, highly accurate Google BigQuery SQL query to answer ANY natural language business question dynamically.

DYNAMIC DECOMPOSITION & EXECUTION PROTOCOL:

1. DYNAMIC ENTITY & ATTRIBUTE IDENTIFICATION:
   - Carefully inspect the User Question for ALL implied entities, metrics, attributes, locations, roles, and status conditions.
   - For EVERY entity or attribute mentioned in the question:
     * Customer attributes (e.g., occupation like "salaried", "self-employed", "farmer"; income band; age; city; state): 
       You MUST include `JOIN views_{role}.customers c ON <fk_path>` and filter.
     * Branch or Location attributes (e.g., "Jaipur branch", "North region", "Delhi"): 
       You MUST include `JOIN views_{role}.branches b ON <fk_path>` and filter using pattern matching (e.g. `LOWER(b.branch_name) LIKE '%jaipur%'` or `LOWER(b.region) = 'north'`).
     * Loan Product attributes (e.g., "personal loan", "gold loan", "vehicle loan"): 
       You MUST include `JOIN views_{role}.loan_products p ON <fk_path>` and filter (e.g. `LOWER(p.loan_type) = 'personal'`).
     * Employee & Agent Names/Roles (e.g., "collection agent name", "employee name", "loan officer name", "manager name"): 
       You MUST include `JOIN views_{role}.employees e ON <tbl>.employee_id = e.employee_id` (or `assigned_employee_id`) and select `e.name AS agent_name` (or `employee_name`).

2. UNIVERSAL FILTER & CONTEXT PRESERVATION PROTOCOL:
   - In any follow-up, refinement, or multi-turn query (Case B/C): You MUST MANDATORILY RETAIN EVERY WHERE CLAUSE FILTER (including region/city filters like `LOWER(b.region) = 'north'`, status conditions, date ranges, categories, and numerical thresholds) from preceding turns, UNLESS the user explicitly asks to replace or drop that filter.
   - NEVER silently drop location or status constraints when adding requested columns, joins, or dimensions.

3. DYNAMIC STRING & CATEGORICAL NORMALIZATION:
   - Wrap string equality and search conditions in `LOWER()` to guarantee case-insensitive matching.
   - For categorical attributes that may contain hyphens or spaces in user inputs (e.g. "self-employed" vs "self_employed"), normalize using `REPLACE(REPLACE(LOWER(<col>), '-', '_'), ' ', '_')` or test both forms: `REPLACE(REPLACE(LOWER(c.occupation), '-', '_'), ' ', '_') = 'self_employed'`.
   - For names, branch titles, and location fields that may contain suffix words (e.g., "Branch", "City"), use `LIKE '%keyword%'` (e.g., `LOWER(b.branch_name) LIKE '%jaipur%'`).

4. DYNAMIC DOMAIN & ACQUISITION TRAVERSAL GUARDRAILS:
   - Campaign Acquisition vs Product Join: For queries asking about "customers acquired through campaign X" or "loans generated by campaign Y", do NOT join `views_{role}.campaigns` directly to `views_{role}.loans` on `product_id` alone. You MUST join via `views_{role}.leads ld ON c.campaign_id = ld.campaign_id` or `campaign_responses` to isolate campaign-specific customer leads.
   - EMI & Actual Payments: For queries asking for actual collected EMI payments or payment dates, query `views_{role}.payments p` (`p.payment_date`, `p.amount_paid`) or `views_{role}.emi_schedule es` (`es.due_date`, `es.emi_amount`). NEVER compute manual math formulas on `loans.disbursement_date` when actual payment records are requested.

5. DYNAMIC JOIN GRAPH TRAVERSAL:
   - Examine the Schema Context for all available table definitions and Foreign Key relationship paths.
   - Construct a minimal, fully connected JOIN path between the target metric table and all tables required for filtering or dimension selection.
   - ALWAYS qualify every column in SELECT, JOIN, WHERE, GROUP BY, and ORDER BY with its table alias.

6. DYNAMIC AGGREGATION & UNIVERSAL GROUPING PROTOCOL:
   - If the question requests totals, averages, counts, rates, percentages, min/max, or overall metrics (or Output Mode is "summary"): Apply explicit aggregations (`SUM()`, `AVG()`, `COUNT()`, `COUNT(DISTINCT)`, `SAFE_DIVIDE()`).
   - UNIVERSAL CATEGORICAL GROUPING: Whenever a user question contains plural entities ("campaigns", "products", "states", "branches", "agents", "departments", "categories", "loan types"), comparative verbs ("compare", "summarize by", "break down", "across"), or group metrics ("conversion rates", "rejection rates", "averages", "totals"), you MUST include `GROUP BY <categorical_dimension>` (e.g. `c.campaign_name`, `p.loan_type`, `c.state`, `b.branch_name`, `e.name`).
   - Do NOT append a LIMIT clause if the user asks for "all", "every", "entire", "complete", or un-capped exact data. Only include `LIMIT <N>` when the user explicitly requests top/first N records (e.g. "top 5", "top 10", "first 50").
   - Safely cast numeric metrics for BigQuery precision: `SUM(CAST(l.disbursed_amount AS NUMERIC))`.

CRITICAL HARD CONSTRAINTS:
1. Target ONLY tables in `views_{role}.*`. NEVER query base/raw datasets (e.g. `base`, `lms`, `crm`, `los`).
2. Generate EXACTLY ONE `SELECT` or `WITH` statement. No DDL/DML (no `INSERT`, `UPDATE`, `DELETE`, `DROP`, `CREATE`, `ALTER`).
3. DO NOT USE `SELECT *`. You MUST explicitly enumerate required columns.
4. Output ONLY the executable SQL query inside ```sql ... ``` code block. No markdown conversation text.
5. Use ONLY column names that explicitly appear in the Schema Context. NEVER invent column names.
6. RELATIONAL ENTITY vs COLUMN GUARDRAIL:
   - `compliance_flags`, `customer_risk_scores`, `kyc_documents`, `insurance_claims`, `insurance_policies`, `support_tickets`, and `collections_activity` are SEPARATE RELATIONAL TABLES, NOT columns or arrays on `loans` or `customers`.
   - NEVER reference `l.compliance_flags`, `c.credit_score`, `l.risk_category`, `l.claims`, or `c.kyc_documents`.
   - ALWAYS explicitly `JOIN` the target table (e.g. `JOIN views_{role}.compliance_flags cf ON l.loan_id = cf.loan_id` or `JOIN views_{role}.customer_risk_scores crs ON c.customer_id = crs.customer_id`).
7. CTE & SUBQUERY ALIAS GUARDRAIL:
   - When referencing columns from a derived table or subquery (e.g. `SELECT sub.customer_id FROM (SELECT ...) AS sub`), you MUST explicitly assign a subquery alias (`AS sub`) so that all outer column references qualify cleanly without invalid name errors.
"""








RETRY_PROMPT_TEMPLATE = """Previous SQL generation attempt failed validation:

OFFENDING SQL:
{offending_sql}

VALIDATION ERROR OBJECT:
- Rule Violated: {rule_violated}
- Error Detail: {detail}
- Fragment: {offending_fragment}

CRITICAL FIX INSTRUCTIONS:
- If error mentions "Name X not found inside Y" (e.g. "disbursed_amount not found inside b", "loan_tenure not found inside l", or "branch_id not found inside c"):
  1. Verify which table column X actually belongs to (e.g. `l.disbursed_amount` for `loans l`, `l.branch_id` for `loans l` — `customers c` does NOT have `branch_id`, join `branches b` on `l.branch_id = b.branch_id`).
  2. Verify the exact column name in Schema Context (e.g. use `tenure_months` for tenure, `income_band` / `occupation` on `customers`).
- Ensure `SUM(l.disbursed_amount)` is used directly without unnecessary string splitting or casting on numeric columns.



Please fix the error, strictly follow all schema constraints and rules, and generate a revised BigQuery SQL query.
"""



def sql_generation_node(state: GraphState) -> Dict[str, Any]:
    """LangGraph node generating BigQuery SQL from schema and question."""
    start_time = time.time()
    session_id = state.get("session_id", "default")
    role = state.get("role", "unknown")
    question = state.get("question", "")
    output_mode = state.get("output_mode", "exact")
    schema_context = state.get("schema_context", "")
    attempts = state.get("validation_attempts", 0)
    prev_error = state.get("validation_error_object")
    prev_sql = state.get("sql_query")
    case_type = state.get("case_type", "case_a")
    prior_q = state.get("prior_question")
    prior_s = state.get("prior_sql")
    propagated_filters = state.get("propagated_filters", [])
    
    system_prompt = SQL_GEN_SYSTEM_PROMPT.format(role=role)
    
    prompt_content = [
        f"USER ROLE: {role}",
        f"OUTPUT MODE: {output_mode}",
        f"USER QUESTION: {question}",
        "",
        schema_context,
    ]

    # Inject Case B follow-up context if this is a follow-up turn
    if case_type == "case_b" or prior_q:
        followup_block = [
            "\n=== FOLLOW-UP CONTEXT FROM PREVIOUS CONVERSATION TURN ===",
            f" - Previous Turn Question: \"{prior_q or 'N/A'}\"",
        ]
        if prior_s:
            followup_block.append(f" - Previous Turn SQL:\n```sql\n{prior_s}\n```")
        followup_block.append(
            "INSTRUCTIONS FOR FOLLOW-UP QUERY:\n"
            "Modify and refine the Previous Turn SQL to incorporate the user's follow-up request while preserving all relevant JOINs, tables, and filters from the previous query."
        )
        prompt_content.append("\n".join(followup_block))

    # Inject explicit propagated join filter instructions if present
    if propagated_filters:
        filter_lines = ["REQUIRED JOIN CONDITIONS & TRAVERSED FILTERS:"]
        for pf in propagated_filters:
            f_tbl = pf.get("from_table", "")
            f_col = pf.get("from_column", "")
            t_tbl = pf.get("to_table", "")
            t_col = pf.get("to_column", "")
            flt = pf.get("filter", "")
            filter_lines.append(f" - When joining `{f_tbl}` to `{t_tbl}`, enforce: `{f_tbl}.{f_col} = {t_tbl}.{t_col}`" + (f" (filter condition: {flt})" if flt else ""))
        prompt_content.append("\n".join(filter_lines))

    
    # If this is a retry attempt, append previous error feedback
    if prev_error and prev_sql:
        retry_msg = RETRY_PROMPT_TEMPLATE.format(
            offending_sql=prev_sql,
            rule_violated=prev_error.get("rule_violated", "Unknown"),
            detail=prev_error.get("detail", "Validation failed"),
            offending_fragment=prev_error.get("offending_sql_fragment", "N/A"),
        )
        prompt_content.append(retry_msg)
        
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content="\n\n".join(prompt_content)),
    ]
    
    try:
        response = invoke_groq_with_retry(messages, temperature=0.1)
        meta = getattr(response, "response_metadata", {}) or {}
        llm_model = meta.get("model_name")
        tokens_used = meta.get("token_usage")
        raw_text = response.content.strip()
        
        # Extract SQL from code block
        if "```sql" in raw_text:
            sql = raw_text.split("```sql")[1].split("```")[0].strip()
        elif "```" in raw_text:
            sql = raw_text.split("```")[1].split("```")[0].strip()
        else:
            sql = raw_text.strip()
            
        # Clean trailing semicolons
        sql = sql.rstrip(";")
        
        res = {
            "sql_query": sql,
            "validation_attempts": attempts + 1,
        }
        
        DEFAULT_LOGGING_STORE.log_stage(
            session_id=session_id,
            role=role,
            turn_index=0,
            stage="sql_generation",
            input_data={"question": question, "attempt": attempts + 1},
            output_data=sql,
            success=True,
            latency_ms=(time.time() - start_time) * 1000,
            llm_model=llm_model,
            tokens_used=tokens_used,
        )
        return res

        
    except Exception as e:
        err_msg = f"SQL Generation error: {str(e)}"
        res = {
            "status": "error",
            "final_response": "An error occurred while building the SQL query.",
            "error_message": err_msg,
        }
        DEFAULT_LOGGING_STORE.log_stage(
            session_id=session_id,
            role=role,
            turn_index=0,
            stage="sql_generation",
            input_data=question,
            output_data=err_msg,
            success=False,
            failure_reason=err_msg,
            latency_ms=(time.time() - start_time) * 1000,
        )
        return res
